/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_cst_bracmat */

#ifndef _Included_dk_cst_bracmat
#define _Included_dk_cst_bracmat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_cst_bracmat
 * Method:    eval
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dk_cst_bracmat_eval
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dk_cst_bracmat
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_dk_cst_bracmat_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dk_cst_bracmat
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dk_cst_bracmat_end
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
